language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - pip install nose coverage
    - pip install coveralls
script:
    - nosetests -s -v --with-coverage --cover-erase --cover-html --cover-html-dir ./coverage
after_success:
    - coveralls